USE [TPN_CRM]
GO
/****** Object:  StoredProcedure [dbo].[scm_daily_report]    Script Date: 12/7/2019 11:57:21 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[scm_daily_report]
(@P_COMP_CODE  varchar (20)  ,
@P_CENT_CODE   varchar (20)  ,
@P_STATE_CODE varchar (20)  ,
@P_CITY_CODE  varchar (20)  ,
@P_TYPE_CODE   varchar (20)  ,
@P_SS_CODE   varchar (20)  ,
@P_DISTRIBUTOR_CODE   varchar (20)  ,
@PFROM_DATE  DATETIME,
@PTO_DATE DATETIME,
@PTYPE varchar (20),
@PUSER_ID  varchar (20)  ,
@P_EXTRA   varchar (50) ,
@P_EXTRA1   varchar (50),
@P_EXTRA2   varchar (50)
)
as
begin

IF @PTYPE='1'
	BEGIN

DECLARE @V_SIZE VARCHAR(20)
DECLARE @V_QUERY VARCHAR(MAX)
DECLARE @V_QUERY1 VARCHAR(MAX)
DECLARE @V_QUERY2 VARCHAR(MAX)='SELECT NULL,NULL,NULL,NULL,''TOTAL''     ,   ''PCS'''
DECLARE @V_QUERY3 VARCHAR(MAX)='SELECT NULL,NULL,NULL,NULL,''TOTAL''     ,   ''CB'''
DECLARE @V_QUERY4 VARCHAR(MAX)='SELECT NULL,NULL,NULL,NULL,''TOTAL''     ,   ''TC'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,''10'''
DECLARE @V_QUERY5 VARCHAR(MAX)='SELECT NULL,NULL,NULL,NULL,''TOTAL''     ,   ''PC'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,''12'''


CREATE TABLE #DAILY_REP(CLIENT_CODE  VARCHAR(100), "RETAILER NAME" VARCHAR(100),	"ADDRESS" VARCHAR(200),	"PHONE NO" VARCHAR(100),	"PRODUCT" VARCHAR(100),"PRODUCT_TYPE" VARCHAR(20))

SET @V_QUERY1='UPDATE #DAILY_REP SET "TTL Pcs"=0'

DECLARE C1 CURSOR LOCAL FOR 
SELECT DISTINCT  SIZE FROM PPC_PRODUCT_SIZE_MAST WHERE QTY_IN_ML<>0
OPEN C1 

FETCH C1 INTO @V_SIZE
WHILE @@FETCH_STATUS=0
BEGIN

SET @V_QUERY='ALTER TABLE #DAILY_REP ADD "'+@V_SIZE +'" VARCHAR(20)'

SET @V_QUERY1=ISNULL(@V_QUERY1,'')+'+ISNULL(CONVERT(NUMERIC(12,2),"'+@V_SIZE +'"),0)'

SET @V_QUERY2=ISNULL(@V_QUERY2,'')+',SUM(ISNULL(CONVERT(NUMERIC(12,2),"'+@V_SIZE +'"),0))'
SET @V_QUERY3=ISNULL(@V_QUERY3,'')+',SUM(ISNULL(CONVERT(NUMERIC(12,2),"'+@V_SIZE +'"),0))'

PRINT '@V_QUERY'
EXEC( @V_QUERY)
FETCH C1 INTO @V_SIZE
END
CLOSE C1
DEALLOCATE C1

ALTER TABLE  #DAILY_REP ADD "TTL Pcs" VARCHAR(20)

SET @V_QUERY2=ISNULL(@V_QUERY2,'')+',SUM(ISNULL(CONVERT(NUMERIC(12,2),"TTL Pcs" ),0)) FROM #DAILY_REP'
SET @V_QUERY3=ISNULL(@V_QUERY3,'')+',SUM(ISNULL(CONVERT(NUMERIC(12,2),"TTL Pcs" ),0)) FROM #DAILY_REP'


DECLARE @V_CLIENT_CODE VARCHAR(20)
DECLARE @V_CLIENT_NAME VARCHAR(200)
DECLARE @V_ADDR1E VARCHAR(200)
DECLARE @V_MOBILE VARCHAR(20)
declare @V_SCM_CODE VARCHAR(20)

DECLARE C2 CURSOR LOCAL FOR
SELECT  CLIENT_CODE, CLIENT_NAME,MOBILE,SCM_CODE,ADDR1 FROM SCM_APP WHERE CREATED_BY=@PUSER_ID AND CONVERT(DATE,CREATION_DATE)=CONVERT(DATE,ISNULL(@PFROM_DATE,GETDATE()))

OPEN C2
FETCH C2 INTO @V_CLIENT_CODE,@V_CLIENT_NAME,@V_MOBILE,@V_SCM_CODE,@V_ADDR1E
WHILE @@FETCH_STATUS=0
BEGIN

DECLARE @V_PRODUCT_CODE VARCHAR(20)
DECLARE @V_PRODUCT_NAME VARCHAR(200)
DECLARE @V_PRODUCT_TYPE_CODE VARCHAR(20)
DECLARE @V_PRODUCT_TYPE_NAME VARCHAR(200)
DECLARE @V_PRODUCT_SIZE_CODE VARCHAR(20)
DECLARE @V_SIZE_NAME VARCHAR(200)
DECLARE @V_ORDER_QTY   VARCHAR(20)

DECLARE C3 CURSOR LOCAL FOR
SELECT PRODUCT_CODE, (SELECT  MISC_MAST_NAME FROM PPC_MISC_MAST
 WHERE MISC_MAST_TYPE='PTM' and  MISC_MAST_CODE IN  (select PRODUCT_TYPE_CODE from PPC_PRODUCT_MAST where  PRODUCT_CODE=a.PRODUCT_CODE))PRODUCT_NAME,
PRODUCT_TYPE_CODE,(SELECT PACKING_TYPE_NAME FROM PPC_PACKING_TYPE_MAST WHERE PACKING_TYPE_CODE=A.PRODUCT_TYPE_CODE)PRODUCT_TYPE_NAME,
PRODUCT_SIZE_CODE,(SELECT SIZE FROM PPC_PRODUCT_SIZE_MAST WHERE SIZE_TYPE_CODE=A.PRODUCT_SIZE_CODE)SIZE_NAME,
ORDER_QTY FROM SCM_APP_CLIENT a WHERE SCM_APP_CODE=@V_SCM_CODE


OPEN C3
FETCH C3 INTO @V_PRODUCT_CODE,@V_PRODUCT_NAME,@V_PRODUCT_TYPE_CODE,@V_PRODUCT_TYPE_NAME,@V_PRODUCT_SIZE_CODE,@V_SIZE_NAME,@V_ORDER_QTY
WHILE @@FETCH_STATUS=0
BEGIN

DECLARE @V_CNT NUMERIC
SELECT @V_CNT=COUNT(*) FROM #DAILY_REP WHERE CLIENT_CODE=@V_CLIENT_CODE AND "PRODUCT"=@V_PRODUCT_NAME AND "PRODUCT_TYPE"=@V_PRODUCT_TYPE_NAME

IF @V_CNT=0
BEGIN

INSERT INTO #DAILY_REP(CLIENT_CODE   ,"RETAILER NAME" ,	"ADDRESS" ,	"PHONE NO" ,	"PRODUCT" ,"PRODUCT_TYPE" )
			   VALUES(@V_CLIENT_CODE ,@V_CLIENT_NAME ,@V_ADDR1E  ,@V_MOBILE   ,@V_PRODUCT_NAME,@V_PRODUCT_TYPE_NAME)

END

SET @V_QUERY='UPDATE #DAILY_REP SET "'+@V_SIZE_NAME+'"='+@V_ORDER_QTY +' where CLIENT_CODE='''+@V_CLIENT_CODE+''' AND  "PRODUCT"='''+@V_PRODUCT_NAME+''' AND "PRODUCT_TYPE"='''+@V_PRODUCT_TYPE_NAME+''''
print '@V_QUERY'
print @V_QUERY

EXEC (@V_QUERY)


FETCH C3 INTO @V_PRODUCT_CODE,@V_PRODUCT_NAME,@V_PRODUCT_TYPE_CODE,@V_PRODUCT_TYPE_NAME,@V_PRODUCT_SIZE_CODE,@V_SIZE_NAME,@V_ORDER_QTY
END
DEALLOCATE C3



FETCH C2 INTO @V_CLIENT_CODE,@V_CLIENT_NAME,@V_MOBILE,@V_SCM_CODE,@V_ADDR1E
END
CLOSE C2
DEALLOCATE C2





PRINT '@V_QUERY1'
PRINT @V_QUERY1

EXEC(@V_QUERY1)


PRINT '@V_QUERY2'
PRINT @V_QUERY2

INSERT INTO #DAILY_REP
EXEC( @V_QUERY2)

INSERT INTO #DAILY_REP
EXEC( @V_QUERY3)

INSERT INTO #DAILY_REP
EXEC( @V_QUERY4)
INSERT INTO #DAILY_REP
EXEC( @V_QUERY5)


SELECT * FROM #DAILY_REP

END
ELSE IF @PTYPE='2'
BEGIN


SELECT   'TC' TOTAL, '10' 'CB'
UNION
SELECT  'PC'  TOTAL, '20' 'CB'

END
ELSE IF @PTYPE='3'
BEGIN


SELECT   'TC' TOTAL, '10' 'CB'
UNION
SELECT  'PC'  TOTAL, '20' 'CB'

END
ELSE IF @PTYPE='4'
BEGIN


SELECT   'HI FOR ALL' MES

END

end